version: '3'
services:
  neo4j:
    container_name: Neo4j-local
    image: neo4j:5
    platform: linux/x86_64
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
    environment:
      # Raise memory limits
    - NEO4J_apoc_export_file_enabled=true
    - NEO4J_apoc_import_file_enabled=true
    - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
    - NEO4J_dbms_memory_heap_initial__size=512m
    - NEO4J_dbms_memory_heap_max__size=2G
    - NEO4J_apoc_uuid_enabled=true
    - NEO4J_dbms_default__listen__address=0.0.0.0
    - NEO4J_dbms_allow__upgrade=true
    - NEO4J_dbms_default__database=multiDeal
    - NEO4J_AUTH=neo4j/local_secret

networks: { Neo4j-local: { } }
volumes:
  Neo4j-local: